### ISSUE TITLE
html page error sources

### ISSUE THREAD

**Issue by androuy** [byt3bl33d3r/MITMf#130]
i can't understand what happened here , this code is shown in several pages that requested from mitmf proxy 
i use this command : 
python mitmf.py -i wlan0 --hsts --spoof --dns --gateway 10.10.10.1
on kali linux 1.1 64_bits 

![aa](https://cloud.githubusercontent.com/assets/12910153/8378054/1dc8f8cc-1c1f-11e5-90dc-6b3c0640b06f.PNG)

![capture](https://cloud.githubusercontent.com/assets/12910153/8378239/a7200236-1c20-11e5-8ca6-bbc75b556d3e.PNG)

**Comment by byt3bl33d3r** [comment]
@androuy hi,
Does this happen only on these two websites?

**Comment by androuy** [comment]
@byt3bl33d3r 
no it's shown in several pages, but i think that when i use the mitmf on network that contain thunder cache server this problem  happen , cause my ISP use thunder cache and  this problem gets him, i use the mitmf without the thunder cache and it's work good.

**Comment by byt3bl33d3r** [comment]
@androuy I've never had an opportunity to test MITMf with a thunder cache server, interesting and thanks for bringing this to my attention. I'm closing the issue since you've seem to have established that this is indeed the problem. will be interesting to see if this is still the case once v0.9.8 comes out. thanks.
