### ISSUE TITLE
upsidedownternet cant flip jpeg's

### ISSUE THREAD

**Issue by WiredLife** [byt3bl33d3r/MITMf#151]
bug or feature?
2015-08-05 14:10:07 192.168.178.241 [type:Chrome-44 os:Windows 7] [Upsidedownternet] Error: decoder jpeg not available

**Comment by byt3bl33d3r** [comment]
neither, Pillow just doesn't support jpeg iirc

**Comment by fbis251** [comment]
I tried this on Kali and Ubuntu 15.04, both just needed libjpeg available.

sudo apt-get install libjpeg-dev
pip install -I pillow

after that upsidedownternet worked with JPEGs just fine. If you're using the root user (for example on Kali), make sure you clear ~/.cache/pip/ since I had trouble getting pillow to recompile with JPEG support after reinstalling it.

**Comment by byt3bl33d3r** [comment]
@fbis251 thanks! added this to the install intructions
