### ISSUE TITLE
Problem with sslstrip in some pages

### ISSUE THREAD

**Issue by andonidiaz** [byt3bl33d3r/MITMf#173]
Im testing the tool with some https pages, and for example I can see how with pages like:
-hotmail.com (live.com)
-youtube.com

The sslstrip works well and gives me the data of the secure posts that corresponds to the credentials entered, but if I test with some others (like facebook.com o mail.google.com) it doesn't work.

Im testing in a "victim PC" with Chrome and W7, the ARP Spoof worked well, as I can see executing arp -a in the DOS CMD.

I cleaned the licenses from the cache and temp data from the chrome browser.

Anybody knows why don't work?

Regards

**Comment by hight0wer** [comment]
It's because hotmail doesn't support HSTS when facebook and google do. The HSTS makes Sslstrip unusable. You can try mitmf with --hsts option (Sslstrip+), but it also doesn't work in most cases for facebook and google. The easier way is to force the victim to use some browser, which doesn't support HSTS like Internet Explorer on W7. Or some older version of browser, then it could work with the --hsts option.
More about HSTS support in browsers here: http://caniuse.com/#feat=stricttransportsecurity
But this question doesn't belong here, this is for bug reports.
Anyway I think many of the people who uses Mitmf tries to hack Facebook creditals and it would be nice if someone finds a way how to get them when the victim uses for example latest version of Chrome, please let us know.
I was able to hack mobile version of Chrome v39 (on Android 5) from time to time, but after update to Chrome v42 it's impossible.
I used this command:
python mitmf.py -i wlan0 --hsts --spoof --arp --dns --gateway 192.168.1.1 --targets 192.168.1.10

**Comment by byt3bl33d3r** [comment]
@hight0wer Just FYI facebook is not a concern for this project, nor do I condone the use of MITMf without prior consent
