### ISSUE TITLE
Continuous Kernel Messages 'unregister_netdevice' after quitting MITMF.

### ISSUE THREAD

**Issue by thedp** [byt3bl33d3r/MITMf#242]
I've recently discovered MITMF and I'm really exited. It comes with some really useful stuff!
Great job guys!!

But I'm having this weird issue after I remove my external Wireless USB adapter (TP-LINK TL-WN722N)

Here is a step-by-step process:

1. ARP poison my network:
```     ./mitmf.py -i wlan0 --spoof --arp --gateway 10.0.0.138```

2. I test that I actually receive the traffic: Another machine on the network surfs to a http site.

3. CTRL+C and wait a few seconds (tried waiting different amounts of time: 1m-5m, same result)
until MITMF says the traffic is restored to normal state.

4. Remove the wireless adapter.

5. After a few seconds receive the following message:
```     
Message from syslogd@ES at Jan  4 03:39:56 ...
      kernel:[ 4105.064278] unregister_netdevice: waiting for wlan0 to become free. Usage count = 14
```

<br/>
**PLEASE NOTE:**
- The message never stops. If keeps being displayed in the shell every few seconds.
It's impossible to shutdown the system without using a hard reboot.
- It's impossible to reconnect the wireless adapter. So far there is nothing I can do about it and `lsusb` doesn't respond.
- So far it seems the issue happens only when I use arp poison, however I haven't tested most of the features.

<br/>
**Summary of what I use:**
Kali 2.0  (VM)
TP-Link TL-WN722N
MITMF v0.9.8 - 'The Dark Side'

**Comment by HAMIDx9** [comment]
Hi, 

I faced this kernel message before. Actually it's a Kernel or Driver bug, which does not decrement net device counter and seems to be a deadlock for device. I can tell you if you use `airmon-ng` start and stop you will see this. So this is not a `MITMf` bug.

Please check your kernel and driver to be updated.

**Comment by thedp** [comment]
@HAMIDx9 Thanks for the reply.
I never had any issues with `airmon-ng`. I've just tested again and I can't reproduce the `unregister_netdevice` with `airmon-ng`.

Can you please provide a step-by-step for how you were managed to reproduce the issue with `airmon-ng`. Thanks.

**Comment by thedp** [comment]
@HAMIDx9 
I've discovered other people are having the `unregister_netdevice` issue on Kali 2.0: https://bugs.kali.org/view.php?id=2558

However, for me at the moment MITMF is the only tool that shows this problem.

Is there a way I can manually release the deadlock?
Or, how should I go on updating the driver?

Thanks.

**Comment by HAMIDx9** [comment]
I had this issue with another card on Kali 1.0 on raspberrypi and upgrading to kernel 4.* fix the issue (I have a custom kernel 4.1.13 now). honestly i don't remember the fix to address here. but there was an issue in kernel. these race conditions usually is hard to release or fix and the best solution is reboot.  Maybe this [link](http://serverfault.com/questions/650377/linux-kernel-bug-w-netns-and-or-xen-guest-unregister-netdevice-waiting-for) can help you to find the exact process if there is any.

I encourage you to patch(Kali injection patch?) and compile most recent kernel and test it. since upgrading kernel in Kali does not happen too often.

Besides we know this is not a `MITMf` issue. Please close this issue and contact me if i can help in the process.

**Comment by thedp** [comment]
@HAMIDx9 I've never tried to compile and install a kernel myself. Honestly, I have no idea how to start :/

**Comment by thedp** [comment]
I've installed a newer kernel: `Linux 49947 4.2.0-0.bpo.1-amd64 #1 SMP Debian 4.2.6-3~bpo8+2 (2015-12-14) x86_64 GNU/Linux` from the Debian repos and the issue stopped. *sigh*

**Comment by byt3bl33d3r** [comment]
@thedp heh, good to know! thanks
