### ISSUE TITLE
[Errno 98]

### ISSUE THREAD

**Issue by Sp3cter-97** [byt3bl33d3r/MITMf#333]
I've through the wiki a whole bunch of times and I've tried to find a fix. Can't fix it. So as a last resort please help.
![problem](https://cloud.githubusercontent.com/assets/21266436/18015939/c9f522d6-6bc1-11e6-9a3e-f434833bf6eb.png)

**Comment by jakuta-tech** [comment]
Looks like you have something already running on port 10000. 

netstat -tulpn | grep :10000

**Comment by Sp3cter-97** [comment]
Thanks for the reply. 
How can I find an open port to run it on and then configure MITMf to run on the open port?

**Comment by jakuta-tech** [comment]
You haven't posted what's running so I'm not sure what it is.  It's a little weird because things don't naturally run on port 10000 so that netstat command above should show you what is running. You could then shut whatever it is down by killing the pid. Kill -15 <pid> and then try running mitmf again. 
From memory,  sslstrip inside mitmf should be the application that wants to run on port 10000 .
If you want to change the port inside mitmf script to run on something weeks then just search the script for the number 10000 and change it to something higher

**Comment by Sp3cter-97** [comment]
Found what was running : 

tcp        0      0 0.0.0.0:10000           0.0.0.0:*               LISTEN      545/python

**Comment by Sp3cter-97** [comment]
Got everything else to work but now I have a problem with the DNS Port. I changed it in dnschef but MITMf still sends the error.

![problem2](https://cloud.githubusercontent.com/assets/21266436/18029309/907600e0-6c8c-11e6-9005-2cf08ab638a9.png)

**Comment by HAMIDx9** [comment]
where did you change dns port?
since it uses logger as:
shutdown("\n[DNS] Unable to start DNS server on port {}: port already in use".format(self.config['MITMf']['DNS']['port']))
so your `config/mitmf.conf` dns port is still 53.

**Comment by byt3bl33d3r** [comment]
If you can't figure this out by yourself, I don't think you should be using this
