### ISSUE TITLE
Error , Could not proxy request: timed out

### ISSUE THREAD

**Issue by root0er** [byt3bl33d3r/MITMf#342]
`2016-09-24 16:01:30 [DNSChef] Could not proxy request: timed out
2016-09-24 16:01:30 [DNSChef] Could not proxy request: timed out
2016-09-24 16:01:30 [DNSChef] Could not proxy request: timed out
2016-09-24 16:01:30 [DNSChef] Could not proxy request: timed out
2016-09-24 16:01:30 [DNSChef] Could not proxy request: timed out
`
What is the reason？anyone

**Comment by root0er** [comment]
@byt3bl33d3r

**Comment by HAMIDx9** [comment]
the cause of this behavior is this line https://github.com/byt3bl33d3r/MITMf/blob/master/core/servers/DNS.py#L328
which you can change to set an higher timeout.
anyway if in this case you don't need dns spoofing for a while i prefer to use twisted resolver instead of dnschef! Simply edit (https://github.com/byt3bl33d3r/MITMf/blob/master/core/sslstrip/ClientRequest.py) and use L#202 instead of L#199.

**Comment by root0er** [comment]
@HAMIDx9，Thanks

**Comment by byt3bl33d3r** [comment]
It will fail over to the regular twisted DNS resolver if it cannot proxy the request with DNSChef. That's just a warning, so there really shouldn't be any issues.

**Comment by z00z** [comment]
If Kali is installed as a virtual machine, then try to disconnect it from all other networks and make sure that its only connected to the the target network.
Check out the following video as this is how I managed to solve it
https://youtu.be/L05ajtU_Lbk

**Comment by MaroofRoy** [comment]
mitmf dns could not proxy request timed out 
got this error on wlan0
