### ISSUE TITLE
SLL don't deleted  on all sites

### ISSUE THREAD

**Issue by h0wk** [byt3bl33d3r/MITMf#400]
I use command 

> mitmf -i wlan0 --spoof --arp  --hsts --dns  --gateway 192.168.8.1

And when i go to google.com I get security connection (https) and i not get traffic  

I use kali and attack windows 7 chrome (firefox show dns error)

**Comment by snappie** [comment]
Sadly, google is immune to SSLstrip because it uses [hsts](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security)
furthermore, the hsts bypass is dead and no longer works.

Google has tight security. I believe (well, at least, expect them too) they also apply [certificate pinning](https://en.wikipedia.org/wiki/HTTP_Public_Key_Pinning), which prevents you from using false certificates no matter how hard you try.
There is currently, as far as I know, no way to impersonate google. Making the website immune to MITM attacks

**Comment by zephrax** [comment]
Its not dead at all. If you can change the target machine time, you can make the certificate expires and then get HSTS bypass working.

https://github.com/myusuf3/delorean

**Comment by byt3bl33d3r** [comment]
It's not dead and Google isn't immune. TL;DR it depends on the browser the target is using: If the target is running Chrome for example it has HSTS preloading, so SSLstripping or the HSTS bypass won't work. on older versions of IE and any other browser that doesn't have HSTS preloading it still should work though.
